#!/bin/bash

usage() { printf 'usage: avi2bov <dir> <avi file>\n' > /dev/stderr; exit 1; }
die()   { printf 'avi2bov: %s\n' "$1"; usage; }

if test $# != 2; then die 'arg count'; fi
d=$1; shift # output directory
avi=$1; shift # input file

if ! test -r "$avi"; then die "cannot read $avi"; fi

t=/tmp/avi2bov.$$
trap 'rm -rf $t; exit $?' 0 1 2 13 15
mkdir -p $t

avi2tiff $t/tiff $avi
if test $? != 0; then die 'avi2tiff faild'; fi

# percentage to crop from every edge
: ${px=0} ${py=0}
croptiff $px $py $t/tiff/*
fliptiff         $t/tiff/*

tiff2pgm $t/pgm  $t/tiff/*
pgm2bov  "$d"    $t/pgm/*

# TEST: avi2bov.t0
# bin=/tmp/avi2bov
# make install BIN=$bin
# export PATH=$bin:$PATH
# export px=42 py=33 # percentage to crop from every edge
# avi2bov bov test_data/small.mpg
# cat bov/000[01].bov  > avi.out.txt
