#!/bin/bash

d=$1; shift # output directory
f=$1; shift # input file

t=/tmp/avi2bov.$$
trap 'rm -rf $t' 1 2 3 15

mkdir -p $t

avi2tiff $t/tiff $f

# percentege to crop from every edge
: ${px=0} ${py=0}
croptiff $px $py $t/tiff/*
fliptiff         $t/tiff/*

tiff2pgm $t/pgm  $t/tiff/*
pgm2bov  "$d"    $t/pgm/*
