#!/bin/bash

msg()   { printf "croptiff: %s\n" "$*" > /dev/stderr; }
usage() { printf 'usage: croptiff <px> <py> <tiff file>\n' > /dev/stderr; exit 1; }
die()   { printf 'croptiff: %s\n' "$*"; usage; }

# [a]wk [e]xpression: ae 1.0+2.0 returns 3.0
ae() ( s='BEGIN {print '"$@"'}'; awk "$s" )
ini () { # uses `px' and `py' to set `lx' and `ly', `dx', `dy'
    local f=$1
    lx=`convert $f -format '%w' info:`
    if test $? != 0; then die wrong image: $f; fi
    ly=`convert $f -format '%h' info:`
    msg old size: $lx $ly

    dx=`ae int '(' $px/100*$lx ')'`
    dy=`ae int '(' $py/100*$ly ')'`

    lx=`ae $lx-2*$dx`
    ly=`ae $ly-2*$dy`

    msg new size: $lx $ly    
}

run() {
    if ! test -r "$1"; then die "cannot read $1"; fi
    convert -type truecolor -crop  ${lx}x${ly}+${dx}+${dy} +repage "$1" $t &&
	mv $t "$1"
}


t=/tmp/croptiff.$$.tiff
trap 'rm -rf $t; exit $?' 0 1 2 3 15

px=$1; shift; if test $# = 0; then die 'arg count'; fi
py=$1; shift; if test $# = 0; then die 'arg count'; fi

if ! test -r "$1"; then die "cannot read $1"; fi

ini $1
for f; do run "$f"; done
