#!/bin/bash

usage() { printf 'usage: fliptiff [tiff files]... >\n' > /dev/stderr; exit 1; }
die()   { printf 'fliptiff: %s\n' "$1"; usage; }

run() {
    if ! test -r "$f"; then die "cannot read $f"; fi
    convert -type truecolor -flip "$f" $t &&
	mv $t "$f"    
}


t=/tmp/croptiff.$$.tiff
trap 'rm -rf $t' 1 2 3 15
for f; do run "$f"; done
